<?php

declare(strict_types=1);

/**
 * Smoke test: compare output files generated by a pre-refactor (legacy) module
 * vs the refactored composer-lib implementation, against the same FA database.
 *
 * This script runs tools/smoke/generate.php in two subprocesses to avoid class
 * name collisions between two module code trees.
 */

function stderr(string $message): void
{
    fwrite(STDERR, $message . PHP_EOL);
}

function stdout(string $message): void
{
    fwrite(STDOUT, $message . PHP_EOL);
}

function fail(string $message, int $code = 1): void
{
    stderr($message);
    exit($code);
}

function usage(): void
{
    $msg = <<<TXT
Usage:
  php tools/smoke/compare.php \
    --fa-root=/path/to/frontaccounting \
    --legacy-module=/path/to/pre-refactor/module \
    --refactor-module=/path/to/refactored/module \
    --prefs-table=ksf_prefs \
    --out-dir=/path/to/write/results \
    [--generators=pricebook,square,woocommerce] \
    [--tb-pref=0_] \
    [--keep-files=1]

What it does:
- Generates outputs using the legacy module (mode=legacy)
- Generates outputs using the refactored module (mode=refactor)
- Compares line-by-line (normalizing CRLF/LF) and reports first differences

Exit codes:
- 0: all requested generators match byte-for-byte after normalization
- 10: one or more generators differ
- 20+: setup/generation failure
TXT;

    stdout($msg);
}

function normalizeLine(string $line): string
{
    return rtrim($line, "\r\n");
}

function sha256(string $path): string
{
    return hash_file('sha256', $path) ?: '';
}

function compareFiles(string $a, string $b): array
{
    $fa = fopen($a, 'rb');
    $fb = fopen($b, 'rb');

    if ($fa === false || $fb === false) {
        return ['equal' => false, 'error' => 'Could not open one of the files'];
    }

    $line = 0;
    $firstDiff = null;

    while (true) {
        $la = fgets($fa);
        $lb = fgets($fb);
        $line++;

        $ea = ($la === false);
        $eb = ($lb === false);

        if ($ea && $eb) {
            break;
        }

        $na = $ea ? null : normalizeLine($la);
        $nb = $eb ? null : normalizeLine($lb);

        if ($na !== $nb && $firstDiff === null) {
            $firstDiff = [
                'line' => $line,
                'legacy' => $na,
                'refactor' => $nb,
            ];
        }

        if ($ea !== $eb) {
            // Different lengths; no point continuing to find first diff.
            if ($firstDiff === null) {
                $firstDiff = [
                    'line' => $line,
                    'legacy' => $na,
                    'refactor' => $nb,
                ];
            }
            // Continue to EOF for counts.
        }

        if ($ea && !$eb) {
            // drain
            while (fgets($fb) !== false) {
                $line++;
            }
            break;
        }
        if ($eb && !$ea) {
            while (fgets($fa) !== false) {
                $line++;
            }
            break;
        }
    }

    fclose($fa);
    fclose($fb);

    return [
        'equal' => ($firstDiff === null),
        'first_diff' => $firstDiff,
    ];
}

function runGenerate(array $args): array
{
    $cmd = escapeshellarg(PHP_BINARY);
    foreach ($args as $arg) {
        $cmd .= ' ' . escapeshellarg($arg);
    }

    $descriptorspec = [
        0 => ['pipe', 'r'],
        1 => ['pipe', 'w'],
        2 => ['pipe', 'w'],
    ];

    $proc = proc_open($cmd, $descriptorspec, $pipes);
    if (!is_resource($proc)) {
        return ['ok' => false, 'exit' => 127, 'stdout' => '', 'stderr' => 'proc_open failed'];
    }

    fclose($pipes[0]);
    $out = stream_get_contents($pipes[1]);
    $err = stream_get_contents($pipes[2]);
    fclose($pipes[1]);
    fclose($pipes[2]);

    $exit = proc_close($proc);

    return [
        'ok' => ($exit === 0),
        'exit' => $exit,
        'stdout' => trim((string)$out),
        'stderr' => trim((string)$err),
        'cmd' => $cmd,
    ];
}

$opts = getopt('', [
    'fa-root:',
    'legacy-module:',
    'refactor-module:',
    'prefs-table:',
    'out-dir:',
    'generators::',
    'tb-pref::',
    'keep-files::',
    'help::',
]);

if (isset($opts['help'])) {
    usage();
    exit(0);
}

$faRoot = $opts['fa-root'] ?? null;
$legacyModule = $opts['legacy-module'] ?? null;
$refactorModule = $opts['refactor-module'] ?? null;
$prefsTable = $opts['prefs-table'] ?? null;
$outDir = $opts['out-dir'] ?? null;
$generatorList = $opts['generators'] ?? 'pricebook,square,woocommerce';
$tbPref = $opts['tb-pref'] ?? null;
$keepFiles = isset($opts['keep-files']) && (string)$opts['keep-files'] === '1';

if (!$faRoot || !$legacyModule || !$refactorModule || !$prefsTable || !$outDir) {
    usage();
    fail('Missing required arguments.', 2);
}

$genNames = array_values(array_filter(array_map('trim', explode(',', (string)$generatorList))));
if (count($genNames) === 0) {
    fail('No generators specified.', 2);
}

$outDirReal = $outDir;
if (!is_dir($outDirReal) && !@mkdir($outDirReal, 0777, true)) {
    fail("Could not create out-dir: {$outDirReal}", 2);
}

$runId = date('Ymd_His');
$runDir = rtrim($outDirReal, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . 'smoke_' . $runId;
if (!@mkdir($runDir, 0777, true)) {
    fail("Could not create run directory: {$runDir}", 2);
}

$genScript = __DIR__ . DIRECTORY_SEPARATOR . 'generate.php';
if (!is_file($genScript)) {
    fail('generate.php not found next to compare.php', 20);
}

$allMatch = true;
$results = [];

foreach ($genNames as $gen) {
    $legacyOut = $runDir . DIRECTORY_SEPARATOR . $gen . '.legacy.csv';
    $refOut = $runDir . DIRECTORY_SEPARATOR . $gen . '.refactor.csv';

    $commonArgs = [
        $genScript,
        '--fa-root=' . $faRoot,
        '--prefs-table=' . $prefsTable,
    ];
    if ($tbPref !== null) {
        $commonArgs[] = '--tb-pref=' . $tbPref;
    }

    $r1 = runGenerate(array_merge($commonArgs, [
        '--module=' . $legacyModule,
        '--mode=legacy',
        '--generator=' . $gen,
        '--out-file=' . $legacyOut,
    ]));

    if (!$r1['ok']) {
        $results[$gen] = ['ok' => false, 'phase' => 'legacy', 'detail' => $r1];
        $allMatch = false;
        continue;
    }

    $r2 = runGenerate(array_merge($commonArgs, [
        '--module=' . $refactorModule,
        '--mode=refactor',
        '--generator=' . $gen,
        '--out-file=' . $refOut,
    ]));

    if (!$r2['ok']) {
        $results[$gen] = ['ok' => false, 'phase' => 'refactor', 'detail' => $r2];
        $allMatch = false;
        continue;
    }

    if (!is_file($legacyOut) || !is_file($refOut)) {
        $results[$gen] = ['ok' => false, 'phase' => 'compare', 'error' => 'Output file missing'];
        $allMatch = false;
        continue;
    }

    $cmp = compareFiles($legacyOut, $refOut);

    $same = ($cmp['equal'] === true);
    if (!$same) {
        $allMatch = false;
    }

    $results[$gen] = [
        'ok' => true,
        'match' => $same,
        'legacy' => [
            'file' => $legacyOut,
            'sha256' => sha256($legacyOut),
        ],
        'refactor' => [
            'file' => $refOut,
            'sha256' => sha256($refOut),
        ],
        'first_diff' => $cmp['first_diff'] ?? null,
    ];
}

$reportPath = $runDir . DIRECTORY_SEPARATOR . 'report.json';
file_put_contents($reportPath, json_encode([
    'run_dir' => $runDir,
    'fa_root' => $faRoot,
    'legacy_module' => $legacyModule,
    'refactor_module' => $refactorModule,
    'prefs_table' => $prefsTable,
    'generators' => $genNames,
    'results' => $results,
], JSON_PRETTY_PRINT));

stdout("Report: {$reportPath}");

foreach ($results as $gen => $res) {
    if (!($res['ok'] ?? false)) {
        stderr("[{$gen}] FAIL during {$res['phase']}");
        if (!empty($res['detail']['stderr'])) {
            stderr($res['detail']['stderr']);
        }
        continue;
    }

    if ($res['match'] === true) {
        stdout("[{$gen}] OK (match)");
        continue;
    }

    stderr("[{$gen}] DIFF");
    if (!empty($res['first_diff'])) {
        $fd = $res['first_diff'];
        stderr("  first differing line: {$fd['line']}");
        stderr('  legacy:   ' . ($fd['legacy'] ?? '<EOF>'));
        stderr('  refactor: ' . ($fd['refactor'] ?? '<EOF>'));
    }
}

if (!$keepFiles && $allMatch) {
    // If everything matches and caller doesn't want artifacts, clean up.
    foreach (glob($runDir . DIRECTORY_SEPARATOR . '*.csv') ?: [] as $csv) {
        @unlink($csv);
    }
}

exit($allMatch ? 0 : 10);
